env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - airbnb
ignorePatterns:
  - 'src/components/Assets/MaintenanceManagement/CalHeatmap/**/*.*'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
settings: {
  'import/resolver': {
    node: {
      extensions: [ '.ts', '.js', '.jsx', '.tsx', '.json', '.d.ts' ],
      paths: [ './src' ]
    }
  }
}
rules: {
  "@typescript-eslint/no-var-requires": [ "off" ],
  "@typescript-eslint/no-explicit-any": "warn",
  "@typescript-eslint/no-non-null-assertion": "off",
  "@typescript-eslint/explicit-function-return-type": ["warn", { allowExpressions: true }],
  "react/jsx-filename-extension": [ 1, { "extensions": [ ".ts", ".tsx" ] } ],
  "react/prop-types": [ "off" ],
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/exhaustive-deps": "error",
  "react/jsx-props-no-spreading": "off",
  'react/require-default-props': "off",
  "react/no-unused-prop-types": "off",
  'react/jsx-curly-brace-presence': [ 2,'always' ],
  'object-curly-spacing': [ 2, 'always' ],
  'react/jsx-one-expression-per-line': [ 'off' ],
  "no-nested-ternary": [ "off" ],
  "import/extensions": [ 0, 'never' ],
  "no-underscore-dangle": "off",
  'no-param-reassign': [ "error", { "props": false } ],
  'no-shadow': 'off',
  'no-unused-vars': 'off',
  "@typescript-eslint/no-unused-vars": ["warn", { "ignoreRestSiblings": true }],
  'no-use-before-define': 'off',
  '@typescript-eslint/no-use-before-define': ['error'],
  '@typescript-eslint/no-shadow': [ 'error' ],
  "import/prefer-default-export": "warn",
  "camelcase": "off",
  "react/react-in-jsx-scope": "off",
  "react/jsx-uses-react": "off",
  "no-unused-expressions": ["warn", { allowShortCircuit: true }],
  "react/jsx-curly-newline": ["warn", "never"],
  "react/jsx-indent": ["warn", 2, { indentLogicalExpressions: true }],
  "no-plusplus": "off",
  "max-len": ["error", 120, 2, {
    ignoreUrls: true,
    ignoreComments: false,
    ignoreRegExpLiterals: true,
    ignoreStrings: true,
    ignoreTemplateLiterals: true
  }],
  react/destructuring-assignment: "warn",
  react/jsx-key: "error",
  "import/no-extraneous-dependencies": ["off"],
  "react/function-component-definition": [2, { "namedComponents": "arrow-function" }],
  "jsx-a11y/label-has-associated-control": "off"
}
